In [2]:
import pandas as pd

c:\Users\Riad\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:61: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [13]:
rows = []
with open("E:\Projects\SQL\Healthcare Project\HealthCare Data\icd10cm_codes_2026.txt", "r", encoding="latin-1") as f:
    for line in f:
        if not line.strip():
            continue
        code = line[0:7].strip()          # positions 1-7
        description = line[8:].strip()    # position 9 to end
        rows.append((code, description))

df = pd.DataFrame(rows, columns=["diagnosis_code", "description"])

In [14]:
df.head()

  diagnosis_code                                        description
0           A000  Cholera due to Vibrio cholerae 01, biovar chol...
1           A001    Cholera due to Vibrio cholerae 01, biovar eltor
2           A009                               Cholera, unspecified
3          A0100                         Typhoid fever, unspecified
4          A0101                                 Typhoid meningitis

In [15]:
def format_icd10(code):
    code = code.strip()
    if len(code) > 3:
        return code[:3] + "." + code[3:]
    return code

In [16]:
rows = []
with open("E:\Projects\SQL\Healthcare Project\HealthCare Data\icd10cm_codes_2026.txt", "r", encoding="latin-1") as f:
    for line in f:
        if not line.strip():
            continue
        raw_code = line[0:7].strip()
        description = line[8:].strip()
        rows.append((format_icd10(raw_code), description))

df_dot = pd.DataFrame(rows, columns=["diagnosis_code", "description"])

In [17]:
df_dot.head()

  diagnosis_code                                        description
0          A00.0  Cholera due to Vibrio cholerae 01, biovar chol...
1          A00.1    Cholera due to Vibrio cholerae 01, biovar eltor
2          A00.9                               Cholera, unspecified
3         A01.00                         Typhoid fever, unspecified
4         A01.01                                 Typhoid meningitis

In [18]:
df_dot.to_csv("E:\Projects\SQL\Healthcare Project\HealthCare Data\icd10_diagnosis.csv", index=False)
print(f"{len(df_dot)} codes written")

74719 codes written